### ISSUE TITLE
Persist State Posibility?

### ISSUE THREAD

**Issue by fcaride** [hosseinmd/react-global-hook#2]
Hi there! really nice approach to this!
I was wondering if there is a way to persist the state using this library.

Thanks

**Comment by fardad-dev** [comment]
Hi
Yes, you can listen state and persist that.
Any store have a addListener, use that for any thing you want to do.
The addListener function, After setState and changes state, will be invoke
```js
function tokenListener(state){
   saveToken(state.token)
};
const sensitiveStatesKey = ["token"];
store.addListener(tokenListener, sensitiveStatesKey)
```

**Comment by fcaride** [comment]
Oh nice good answer! Thanks!
