### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by DesarrolloMus** [hosseinmd/react-global-hook#3]
Can you provide an example of a minimun application? Its not clear how to use the library.

Thanks!

**Comment by fardad-dev** [comment]
Hi dear,
Provided an Example of [Todo list](https://codesandbox.io/s/react-global-hook-tpc3y) application on the code sandbox.
I hope that helps you.
Feel free to ask if you have any questions.

**Comment by DesarrolloMus** [comment]
Thank you so much!
