### ISSUE TITLE
A way to reset state to initialState

### ISSUE THREAD

**Issue by DesarrolloMus** [hosseinmd/react-global-hook#4]
Hi, 
Is it a way to reset the state to the initial values?

Im doing store.setState(initialState); 
But its not working

Thanks

**Comment by fardad-dev** [comment]
Hi dear,
It should actually work.
Can I see your code for help?

**Comment by fardad-dev** [comment]
I found it,
This is solved in https://github.com/hosseinmd/react-global-hook/commit/ae29350ae481647e233691eca7ebbc7e0bea9e5a

Please update version to 1.3.3

**Comment by DesarrolloMus** [comment]
Oh nice! Thanks its working fine now!
