### ISSUE TITLE
Issue with Fast Refresh

### ISSUE THREAD

**Issue by fcaride** [hosseinmd/react-global-hook#5]
Hi there!

I have an issue in react native with fast refresh. When i change one action file for some reason it changes the state to the initialState. (i have all separated in action files).

Thanks!

**Comment by fardad-dev** [comment]
Can I see the code?

**Comment by fcaride** [comment]
```
import AsyncStorage from '@react-native-community/async-storage';
import { createStore, createHooks } from 'react-global-hook';
import { initialState } from '../initialState';
import * as actions from './actions';

const store = createStore(initialState, actions);
const useGlobal = createHooks(store);

function tokenListener(state) {
  AsyncStorage.setItem('state', JSON.stringify(state));
}

function downloadedListener(state) {
  if (Object.keys(state.downloaded.trackHash).length > 0) {
    AsyncStorage.setItem('downloaded', JSON.stringify(state.downloaded));
  }
}

const sensitiveStatesKey = [
  'albums',
  'artists',
  'mostOpened',
  'myPlaylists',
  'playlists',
  'radios',
  'login',
  'user',
  'notifications'
];
store.addListener(tokenListener, sensitiveStatesKey);
store.addListener(downloadedListener, ['downloaded']);

export default useGlobal;

```

**Comment by fcaride** [comment]
this is my hookStore.js

**Comment by fcaride** [comment]
For some reason when i save an action file it re runs this code and set initialState again (in the createStore function) and deletes the previous state

**Comment by fardad-dev** [comment]
I know what is your problem. I'm working on it.
if I find a way, I'll tell you.

**Comment by fcaride** [comment]
I just saw it thank you!

**Comment by fcaride** [comment]
Could you find a way? Somehow inside the library it should check if there is a previous state or something

**Comment by fardad-dev** [comment]
Yes.
A Good way to solve this is using provider. For that I have to change something in the code structure.
I wrote some code last night and I will release a beta version few days next.

**Comment by fcaride** [comment]
Nice! Thank you!!

**Comment by fardad-dev** [comment]
I have released the next version, you can test that.
You can install that with `$ yarn add react-global-hook@next`.
Read README on the Develop branch.

What must matter
1- import Provider on top of your app
```js
const App = () => (
  <Provider store={Store}>
      ///
  </Provider>
);
```
2-change actions definitions like this
```js
const actions = ({ setState, getState }) => ({
  add(num) {
    const { count } = getState();
    setState({
      count: count+num
    });
  },
});
```
3- don't use Store.state, you can use Store.getState() or Store.useState() in component 

Please let me know if anything happens.

**Comment by fardad-dev** [comment]
On the next release, fast refresh works well but you should take care of that because maybe side effects happen.

**Comment by fcaride** [comment]
Thank you so much when i have some time ill test it!

**Comment by fcaride** [comment]
Is it necesary to make so many changes?

**Comment by fcaride** [comment]
there is no way to work around this? i have to change all the project. I dont even know how to use multiple action files

**Comment by fardad-dev** [comment]
In the previous version, before anything happens, the store is binding to action first parameter. And it does not have a good scene. However, I changed that, it is not because of your issue.

I think you could use actions this way.
```js
const actions = ({ setState, getState }) => ({
  subActions: subActions({ setState, getState }),
  subActions2: subActions2({ setState, getState }),
  //or
  ...(spreadActions({ setState, getState })),
  anAction:()=>{
  ....
  }
});

// subActions files
const subActions = ({ setState, getState }) => ({
  anAction:()=>{
  ....
  },
  ... 
});
```

**Comment by fardad-dev** [comment]
I want to move next version to the final version.
I would like to know, did you have a problem?

**Comment by fcaride** [comment]
Hey there! i couldnt test it i have no time, we have a lot of deadlines. When i can i will notify.

Thanks!
